MYSQL_CONFIG:
  HOST: localhost
  PORT: "3306"
  USERNAME: root
  PASSWORD: secret
  DATABASE: flashcard
  OPTIONS: parseTime=true

PORT: "8080"

ACCESS_KEY_SECRET: fjoapsdifjodpfi
REFRESH_KEY_SECRET: fahdfkajfhieu
