ALTER TABLE cards
    ADD COLUMN easiness_factor FLOAT NOT NULL DEFAULT 2.5,
    ADD COLUMN study_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN repetition_number INT NOT NULL DEFAULT 0;
